import type { Metadata } from "next";
import { Smooch_Sans } from "next/font/google";
import { Header } from "./components/header";
import {Footer} from "./components/footer"
import "./globals.scss";

const smooch_Sans = Smooch_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-br">
      <body className={smooch_Sans.className}>
        <Header/>
        {children} {/* toda página entra aqui */}
        <Footer/>
      </body>
    </html>
  );
}
